#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../common.sh"

LIGHTLLM_LOW_ACCEPT_DIR="${SCRIPT_DIR}"
LIGHTLLM_LOW_ACCEPT_GSM8K_DATASET="${LIGHTLLM_LOW_ACCEPT_GSM8K_DATASET:-${LIGHTLLM_PROJECT_ROOT}/datasets/gsm8k.json}"
LIGHTLLM_LOW_ACCEPT_DATASET="${LIGHTLLM_LOW_ACCEPT_DATASET:-${LIGHTLLM_PROJECT_ROOT}/dataset/random_synth_low_accept_1k.json}"
LIGHTLLM_LOW_ACCEPT_BENCH_SCRIPT="${LIGHTLLM_LOW_ACCEPT_BENCH_SCRIPT:-${LIGHTLLM_SPEC_DIR}/bench_throughput.sh}"
LIGHTLLM_LOW_ACCEPT_HELPER_SCRIPT="${LIGHTLLM_LOW_ACCEPT_HELPER_SCRIPT:-${LIGHTLLM_SPEC_DIR}/helper.py}"
LIGHTLLM_LOW_ACCEPT_MIX_SCRIPT="${LIGHTLLM_LOW_ACCEPT_MIX_SCRIPT:-${LIGHTLLM_LOW_ACCEPT_DIR}/build_ratio_mixed_dataset.py}"
LIGHTLLM_LOW_ACCEPT_QWEN32_DIR="${LIGHTLLM_LOW_ACCEPT_QWEN32_DIR:-${LIGHTLLM_SPEC_DIR}/qwen3-32b}"
LIGHTLLM_QWEN3_32B_TOKENIZER="${LIGHTLLM_QWEN3_32B_TOKENIZER:-/mtc/models/qwen3-32b}"

export LIGHTLLM_LOW_ACCEPT_DIR
export LIGHTLLM_LOW_ACCEPT_GSM8K_DATASET
export LIGHTLLM_LOW_ACCEPT_DATASET
export LIGHTLLM_LOW_ACCEPT_BENCH_SCRIPT
export LIGHTLLM_LOW_ACCEPT_HELPER_SCRIPT
export LIGHTLLM_LOW_ACCEPT_MIX_SCRIPT
export LIGHTLLM_LOW_ACCEPT_QWEN32_DIR
export LIGHTLLM_QWEN3_32B_TOKENIZER
