name: Pre-commit checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install-hooks

    - name: Get list of modified files
      id: files
      run: |
        echo "MODIFIED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})" >> $GITHUB_ENV
        echo $GITHUB_ENV

    - name: Run pre-commit on modified files
      run: |
        if [ -n "${{ env.MODIFIED_FILES }}" ]; then
          pre-commit run --files ${{ env.MODIFIED_FILES }}
        else
          echo "No files to check"
        fi
